### ISSUE TITLE
slot doesn't bind :src on img tag

### ISSUE THREAD

**Issue by Robthegod23** [codekraft-studio/vue-justified-layout#1]
Using the example markup from your repo:

```
<vue-justified-layout :items="images" test.sync="prova" :options.sync="boxesOptions" class="random">
  <template slot="inner" slot-scope="item">
    <img class="inner" :src="item.url" @click="removeItem(item.index)" />
  </template>
</vue-justified-layout>
```
        images: [{
          width: 500,
          height: 450,
          url: 'https://placehold.it/500/450'
        }, {
          width: 640,
          height: 380,
          url: 'https://placehold.it/640/380'
        }, {
          width: 440,
          height: 620,
          url: 'https://placehold.it/440/620'
        }]
the `:src` of the img tag is never binded with `img.url` but returns undefined. Same happens if I try to bind it to a `background-image` : 

`<div v-bind:style="{ 'background-image': 'url(' + item.url + ')' }" />`

Here is a shot of the element in the inspector:

![screen shot 2018-06-07 at 2 40 07 am](https://user-images.githubusercontent.com/13503681/41082381-224be048-69fc-11e8-8686-2bc725974d75.png)

**Comment by b4dnewz** [comment]
hello thanks for the report and thanks for using this module! 
this evening after work I'll look at it

**Comment by b4dnewz** [comment]
Ok, I realized the example was wrong, since the [scoped-slots](https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots) may have multiple properties the example needs to be using `slotProps.item.url` :
```html
<vue-justified-layout :items="imagesList">
  <template slot="inner" slot-scope="slotProps">
    <img :src="slotProps.item.url" />
  </template>
</vue-justified-layout>
```
But with es6 you can also destructure like seen in [vue documentation](https://vuejs.org/v2/guide/components-slots.html#Destructuring-slot-scope) like this:
```html
<vue-justified-layout :items="imagesList">
  <template slot="inner" slot-scope="{item}">
    <img :src="item.url" />
  </template>
</vue-justified-layout>
```

So your example should work with:
```html
<template slot="inner" slot-scope="{item}">
    <div v-bind:style="{ 'background-image': 'url(' + item.url + ')' }" />
</template>
```
I've updated the readme and the demo, many thanks!
