### ISSUE TITLE
Why cannot show the url image?

### ISSUE THREAD

**Issue by mazeteam** [codekraft-studio/vue-justified-layout#3]
Why cannot show the url image?

I follow your example but not work?
<VueJustifiedLayout :items="items" :options="options" />

>  data() {
    return {
      options: {
        targetRowHeight: 250
      },
      items: [{
        width: 250,
        height: 400,
        url: 'https://source.unsplash.com/featured/250x400?green,blue'
      }, {
        width: 300,
        height: 400,
        url: 'https://source.unsplash.com/featured/250x400?green,blue'
      }]
    };
  },

**Comment by b4dnewz** [comment]
Can you post any browser error or reproduce it in a plunkr or another tool like it?

With the code you posted I've very few information to understand what might is not working.

**Comment by mazeteam** [comment]
ok, I just solve the problem in the "close issue"

I want to ask something is about responsive

I try to add a listener for resize , but look like nothave effect

when my container is up to 992px 
the layout will like this
![image](https://user-images.githubusercontent.com/44782630/49700828-d48c8f00-fc1e-11e8-9da0-9f9a88dfea64.png)

I I need add which setting can make look like this layout
![image0](https://user-images.githubusercontent.com/44782630/49700836-f4bc4e00-fc1e-11e8-8ca2-12394617872a.jpg)

```js
<vue-justified-layout :items="jLayout02.imageList" :options="jLayout02.options">
  <template slot="inner" slot-scope="{item}">
    <img :src="item.url" style="width:inherit; height:inherit">
  </template>
</vue-justified-layout>

export default {
  name: "JustifiedLayout",
  data() {
    return {
      jLayout02: {
        imageList:[{
          width: 720,
          height: 800,
          url: "/img/home/520x800.jpg"
        },{
          width: 1050,
          height: 735,
          url: "/img/home/1050x735.jpg"
        }],
        options: {
          targetRowHeight: 250,
          // fullWidthBreakoutRowCadence: true
        }
      },
    };
  },
  components: {
    VueJustifiedLayout,
  },
  methods: {
    onResize () {
      this.$set(this.jLayout01.options, 'containerWidth', this.$el.clientWidth);
      this.$emit('update:options', this.jLayout01.options);
    }
  },
  mounted () {
    this.$set(this.jLayout01.options, 'containerWidth', this.jLayout01.options.containerWidth || this.$el.clientWidth)
    window.addEventListener('resize', this.onResize)
  },
  beforeDestroy () {
    window.removeEventListener('resize', this.onResize)
  }
};
```

**Comment by b4dnewz** [comment]
Hi, i'm not sure if I understood correctly what is your problem but, the plugin will listen for element resize by itself, [see the code](https://github.com/codekraft-studio/vue-justified-layout/blob/master/src/components/JustifiedLayout.vue#L54-L57) and update the __containerWidth__ in user provided options and it will recalculate the best geometry for the layout.

If you want you can play with the targetRowHeight to encrease/reduce the number of rows, than other view results are purely based on the images sizes (or rateo)

**Comment by mazeteam** [comment]
OK
I just upload to server for demo
http://sicgal.com/

when try to responsive
why the screen is large (bigger than 1200 ) then the second row will not full width
that the mean cannot like a photo
wan to the layout in 768px will look like in to the photo (layout)
![image0](https://user-images.githubusercontent.com/44782630/49746857-0ebc6600-fcdd-11e8-892a-f0aa778a6d90.jpg)

**Comment by b4dnewz** [comment]
Ok now I undestand.. actually I'm not sure about the solution, but i'm sure about the "problem".
Since the first image has a width of `1xxx` it will be displayed as wide as possible on wider screens, you have two options here I think:

#### First option

Add a `aspectRatio: x` property to your `items` array for example:

```js
imageList:[{
          width: 720,
          height: 800,
          url: "/img/home/520x800.jpg"
},{
          width: 1050,
          height: 735,
          aspectRatio: 0.5,  // <-- this line should reduce the image ratio
          url: "/img/home/1050x735.jpg"
}],
```

#### Using options

I see in the [flickr](http://flickr.github.io/justified-layout/) official documentation that exist an option called `forceAspectRatio` you should try it, maybe in combination with the first option.

I didn't have tested this case, basically it's not a project issue (i think) it depends to the images you want to display. 

Can you test one or both of the code above? I'll be glad to help further if possible.

**Comment by mazeteam** [comment]
OK, I understand, 

just first time make a this layout, thank you for your help
