### ISSUE TITLE
Usage of `transform: translate(x:,y:)`?

### ISSUE THREAD

**Issue by EternalBlack** [codekraft-studio/vue-justified-layout#6]
I was just wondering if there is any particular reason why `position` + `top`&`left` is used over `transform:translate`? 🤔
As far as I know `transform:translate` is far superior to `position` in terms of performance due to leveraging the GPU's render layer (especially noticeable  with large amounts of data).

**Comment by b4dnewz** [comment]
actually this repository is only a vue adaptation of an [existing plugin ](https://github.com/flickr/justified-layout) made by flickr, all the questions related to it's behaviour should be asked there
